# Generated by Django 5.0.6 on 2024-05-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_titlestring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='endDate',
            field=models.CharField(default='Present', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='startDate',
            field=models.CharField(max_length=50),
        ),
    ]
