# Generated by Django 5.0.6 on 2024-05-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_experience_enddate_alter_experience_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issued_by', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('description', models.TextField()),
                ('certificate_file', models.FileField(upload_to='certificates/')),
            ],
        ),
    ]
